### ISSUE TITLE
ImportError: The _imagingft C module is not installed

### ISSUE THREAD

**Issue by lefranz** [freedomofpress/trackthenews#13]
I tried everything I could before posting here, sorry. I can't get passed this error. It seems pretty common with pillow...
I'm on Ubuntu 16.04
Any idea? Thank you!

Matching against the following words: ['Hamas']
Checking Le Monde article 1/19
Got one!
Traceback (most recent call last):
  File "/usr/local/bin/trackthenews", line 9, in <module>
    load_entry_point('trackthenews==0.1.9.1', 'console_scripts', 'trackthenews')()
  File "/usr/local/lib/python3.5/dist-packages/trackthenews-0.1.9.1-py3.5.egg/trackthenews/core.py", line 444, in main
    article.tweet()
  File "/usr/local/lib/python3.5/dist-packages/trackthenews-0.1.9.1-py3.5.egg/trackthenews/core.py", line 95, in tweet
    self.imgs.append(render_img(graf, square=square))
  File "/usr/local/lib/python3.5/dist-packages/trackthenews-0.1.9.1-py3.5.egg/trackthenews/core.py", line 147, in render_img
    fnt = ImageFont.truetype(font_path, size=36)
  File "/usr/local/lib/python3.5/dist-packages/Pillow-5.0.0-py3.5-linux-x86_64.egg/PIL/ImageFont.py", line 260, in truetype
  File "/usr/local/lib/python3.5/dist-packages/Pillow-5.0.0-py3.5-linux-x86_64.egg/PIL/ImageFont.py", line 135, in __init__
  File "/usr/local/lib/python3.5/dist-packages/Pillow-5.0.0-py3.5-linux-x86_64.egg/PIL/ImageFont.py", line 39, in __getattr__
ImportError: The _imagingft C module is not installed

**Comment by jfilter** [comment]
I also had problem with Pillow and Python 3.x so I resorted to Python 2.7 which works fine. Does it work for you as well?

**Comment by lefranz** [comment]
It worked! Thanks!
