### ISSUE TITLE
403 Error because tweets are too long

### ISSUE THREAD

**Issue by fakebenjay** [freedomofpress/trackthenews#21]
Hey,
I've been running the `trackthenews` script and when it encounters an article title that's too long, it returns a 403 error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.5/bin/trackthenews", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/trackthenews/core.py", line 441, in main
    article.tweet()
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/trackthenews/core.py", line 115, in tweet
    twitter.update_status(status=status, media_ids=media_ids)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twython/endpoints.py", line 114, in update_status
    return self.post('statuses/update', params=params)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twython/api.py", line 268, in post
    return self.request(endpoint, 'POST', params=params, version=version)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twython/api.py", line 258, in request
    api_call=url)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twython/api.py", line 194, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonError: Twitter API returned a 403 (Forbidden), Tweet needs to be a bit shorter.
```

Is there a workaround for this?

**Comment by thisisparker** [comment]
Hm, no, I hadn't run into that! It's easy enough to truncate (probably with a `…`) which I should include in a new version. Out of curiosity, what story has such a long title?

**Comment by fakebenjay** [comment]
Also, while I'm on this issue, I've also gotten a `KeyError: title` traceback error. Any idea what that might be?

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.5/bin/trackthenews", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/trackthenews/core.py", line 420, in main
    articles = parse_feed(outlet, url, delicate, redirects)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/trackthenews/core.py", line 185, in parse_feed
    title = entry['title']
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'title'
```

**Comment by thisisparker** [comment]
Huh, that would happen if an RSS feed entry doesn't have the (required) title field, probably. It doesn't happen much (I haven't seen it in the wild!) but I guess people put all kinds of RSS feeds out there, huh? This should probably fail a little more gracefully, though! Thanks for the report!

**Comment by fakebenjay** [comment]
Thank you! Will try running without that problem feed temporarily...

**Comment by thisisparker** [comment]
Yes, and honestly it should probably tweet without a title just as it does without an `outlet`. I'll plan to fix that, thank you!

**Comment by matthewmcvickar** [comment]
I've submitted a PR that I think addresses this: https://github.com/freedomofpress/trackthenews/pull/22

**Comment by matthewmcvickar** [comment]
And another that addresses potentially empty title/URL: https://github.com/freedomofpress/trackthenews/pull/23
